---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: debian:buster
  commands:
  - apt update
  - apt install -y dos2unix wget zip ca-certificates
  - ./scripts/build.sh

trigger:
  ref:
    exclude:
    - "refs/tags/v*"

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: kobopatch
  image: debian:buster
  commands:
  - apt update
  - apt install -y wget ca-certificates
  - "wget -O kobopatch 'https://github.com/geek1011/kobopatch/releases/download/v0.14.0/kobopatch-linux-64bit'"
  - chmod +x kobopatch

- name: 4.9.11311
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.9.11311 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.9.11314
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.9.11314 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.10.11591
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.10.11591 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.10.11655
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.10.11655 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.11.11911
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.11.11911 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.11.11976
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.11.11976 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.11.11980
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.11.11980 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.11.11982
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.11.11982 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.11.12019
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.11.12019 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.12.12111
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.12.12111 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.13.12638
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.13.12638 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.14.12777
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.14.12777 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.15.12920
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.15.12920 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.16.13162
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.16.13162 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

- name: 4.17.13651
  image: debian:buster
  commands:
  - "bash -c 'export PATH=\"$PWD:$PATH\"; set -o pipefail; ./scripts/test.sh 4.17.13651 | tr \"\\r\" \"\\n\"'"
  depends_on:
  - kobopatch

---
kind: pipeline
name: build-release

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: debian:buster
  commands:
  - apt update
  - apt install -y dos2unix wget zip ca-certificates
  - ./scripts/build.sh

- name: release
  image: plugins/release
  settings:
    api_key:
      from_secret: github_token
    files:
    - "build/*"
    title: "${DRONE_TAG}"

trigger:
  ref:
  - "refs/tags/v*"

depends_on:
- test

...
