dist: xenial
language: go
go:
 - 1.10.5

addons:
  apt:
    update: true
    packages:
      - dos2unix
      - wget
      - zip

install: 
  - go get github.com/tcnksm/ghr
  - go get github.com/geek1011/kobopatch/...

script:
  - bash scripts/build.sh
  - bash scripts/test.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ghr $TRAVIS_TAG build/
  on:
    tags: true
    branch: master
