language: generic
sudo: true

addons:
  apt:
    update: true
    packages:
      - dos2unix
      - wget
      - zip

install: 
  - wget http://security.ubuntu.com/ubuntu/pool/main/w/wget/wget_1.17.1-1ubuntu1.4_amd64.deb
  - sudo dpkg -i *.deb
  - sudo apt -fy install

script:
  - bash scripts/build.sh

deploy:
  provider: script
  on:
    tags: true
    branch: master
  script: echo "Not implemented yet"