language: generic
sudo: true

addons:
  apt:
    update: true
    packages:
      - dos2unix
      - wget
      - zip

install: true
script:
  - bash scripts/build.sh

deploy:
  provider: script
  on:
    tags: true
    branch: master
  script: echo "Not implemented yet"